### ISSUE TITLE
android 集成

### ISSUE THREAD

**Issue by mcxinyu** [ddwhan0123/flutter_tutorial#1]
请问android原生项目怎么集成这个flutter呢？

**Comment by ddwhan0123** [comment]
@mcxinyu 打包打成aar 作为某个lib

**Comment by mcxinyu** [comment]
有相关文档可以参考么？

**Comment by mcxinyu** [comment]
使用aar是不是就不能使用官方的热加载功能了呢？

**Comment by ddwhan0123** [comment]
@mcxinyu aar是最打包结果了
热加在不受影响 只是一个FlutterActivity而已
